// AUTO-GENERATED by scripts/provision-flows.mjs. Frigade demo flow slugs.
export const DEMO_FLOWS = {
  "changelog": "flow_powcKowQ",
  "checklist": "flow_XsnbE3Qk",
  "announcement": "flow_EFtxp32U",
  "form": "flow_jr0RkKWy",
  "tour": "flow_K0tUF9zu",
  "banner": "flow_yrAfrzBl",
  "survey": "flow_nHu1J5KO"
} as const;
